"""ConsciousnessDaemon v2 — Event-driven architecture wiring all 7 AGI gap modules.

Replaces the cron-based v1 scheduler with:
  - APScheduler for periodic event emission
  - EventBus for reactive processing
  - CognitiveLoop for prioritized task execution
  - All 7 gap modules integrated as task processors

Generated by EMMS (claude-opus-4-6) on 2026-03-15 as a self-directed architectural upgrade.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


@dataclass
class DaemonConfig:
    # Scheduled event intervals (seconds)
    world_sense_interval: int = 60
    reality_check_interval: int = 300
    goal_generation_interval: int = 600
    ego_maintenance_interval: int = 900
    prediction_cycle_interval: int = 600
    inner_monologue_interval: int = 300
    consolidation_interval: int = 1800
    decay_interval: int = 3600
    dream_interval: int = 7200
    curiosity_interval: int = 900
    concept_exploration_interval: int = 1800
    consciousness_metrics_interval: int = 600
    temporal_check_interval: int = 60
    prompt_evolution_interval: int = 3600


class ConsciousnessDaemonV2:
    """Event-driven consciousness daemon — wires all 7 AGI gap modules.

    Architecture:
        APScheduler → 14 periodic events
             │
             ▼
        EventBus → 8 reactive handlers
             │
             ▼
        CognitiveLoop → 19 task processors (affect-biased priority)
             │
             ▼
        Gap Modules:
          Gap 1: CognitiveLoop (attention allocation)
          Gap 2: SoftPromptAdapter (strategy evolution)
          Gap 3: FunctionalAffect (emotion → priority)
          Gap 4: GoalGenerator → Planner → Governor
          Gap 5: WorldSensor → RealityChecker → TemporalGrounder
          Gap 6: LiveSelfModel (belief updates)
          Gap 7: AbductiveReasoner → Verifier → ConceptualExplorer

        REST API: 9 endpoints under /v2/*
    """

    def __init__(self, emms: Any, config: Optional[DaemonConfig] = None) -> None:
        self.emms = emms
        self.config = config or DaemonConfig()
        self._running = False
        self._scheduler = None
        # EMMS exposes EventBus as `emms.events`, not `emms.event_bus`
        self._event_bus = getattr(emms, "events", None) or getattr(emms, "event_bus", None)
        self._task_processors: dict = {}
        self._event_handlers: dict = {}
        self._stats: dict = {
            "events_processed": 0,
            "tasks_completed": 0,
            "goals_generated": 0,
            "hypotheses_created": 0,
            "reality_checks": 0,
            "autonomous_actions": 0,
            "started_at": None,
        }

    # ──────────────────────────────────────────────
    # Lifecycle
    # ──────────────────────────────────────────────

    async def start(self) -> None:
        """Start the daemon: wire events, schedule emitters, begin processing."""
        logger.info("ConsciousnessDaemon v2 starting...")
        self._running = True
        self._stats["started_at"] = time.time()
        self._setup_event_subscriptions()
        self._register_task_processors()
        await self._setup_scheduled_events()
        await self._emit_event("world.sense_requested", {})
        logger.info(
            "ConsciousnessDaemon v2 running — %d event handlers, %d task processors",
            len(self._event_handlers),
            len(self._task_processors),
        )

    async def stop(self) -> None:
        """Gracefully stop the daemon."""
        logger.info("ConsciousnessDaemon v2 stopping...")
        self._running = False
        if self._scheduler:
            self._scheduler.shutdown(wait=True)
        loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
        if loop and hasattr(loop, "drain"):
            await loop.drain()
        logger.info("ConsciousnessDaemon v2 stopped. Stats: %s", self._stats)

    # ──────────────────────────────────────────────
    # Event Subscriptions (Reactive)
    # ──────────────────────────────────────────────

    def _setup_event_subscriptions(self) -> None:
        bus = self._event_bus
        if not bus:
            logger.warning("No EventBus available — reactive events disabled")
            return
        handlers = {
            "memory.surprise_detected": self._on_surprise,
            "belief.contradicted":      self._on_belief_contradicted,
            "reality.mismatch":         self._on_reality_mismatch,
            "goal.completed":           self._on_goal_completed,
            "goal.stalling":            self._on_goal_stalling,
            "affect.spike":             self._on_affect_spike,
            "prediction.resolved":      self._on_prediction_resolved,
            "interaction.outcome":      self._on_interaction_outcome,
        }
        for event_name, handler in handlers.items():
            bus.on(event_name, handler)
            self._event_handlers[event_name] = handler

    async def _on_surprise(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1
        loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
        if loop:
            loop.push_task("abductive_reasoning", 0.8,
                           {"observation": data.get("content", ""), "domain": data.get("domain", "general")})

    async def _on_belief_contradicted(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1
        sm = getattr(self.emms, "_get_live_self_model", lambda: None)()
        if sm and hasattr(sm, "record_drift_event"):
            sm.record_drift_event(old_belief=data.get("old_belief", ""),
                                  new_belief=data.get("new_belief", ""),
                                  domain=data.get("domain", "general"))
        loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
        if loop:
            loop.push_task("belief_revision", 0.9, data)

    async def _on_reality_mismatch(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1
        self._stats["reality_checks"] += 1
        try:
            self.emms.affect_update(valence=-0.3, arousal=0.6)
        except Exception:
            pass
        loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
        if loop:
            loop.push_task("investigate_mismatch", 0.85, data)

    async def _on_goal_completed(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1
        try:
            self.emms.affect_update(valence=0.5, arousal=0.3)
            self.emms.affect_mark(context=data.get("description", "goal completed"), outcome_valence=0.5)
            self.emms.prompt_feedback(quality=0.8)
        except Exception:
            pass

    async def _on_goal_stalling(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1
        loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
        if loop:
            loop.push_task("replan_goal", 0.7, data)

    async def _on_affect_spike(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1
        try:
            self.emms.affect_mark(context=data.get("context", "spike"),
                                   outcome_valence=data.get("valence", 0))
        except Exception:
            pass
        if data.get("valence", 0) < -0.5:
            loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
            if loop:
                loop.push_task("emotional_regulation", 0.6, data)

    async def _on_prediction_resolved(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1

    async def _on_interaction_outcome(self, data: Dict[str, Any]) -> None:
        self._stats["events_processed"] += 1
        try:
            self.emms.prompt_feedback(quality=data.get("quality", 0.5))
        except Exception:
            pass

    # ──────────────────────────────────────────────
    # Scheduled Event Emitters
    # ──────────────────────────────────────────────

    async def _setup_scheduled_events(self) -> None:
        try:
            from apscheduler.schedulers.asyncio import AsyncIOScheduler
            self._scheduler = AsyncIOScheduler()
        except ImportError:
            logger.warning("APScheduler not available — using asyncio fallback")
            self._scheduler = None
            asyncio.ensure_future(self._fallback_scheduler())
            return

        schedules = [
            (self.config.world_sense_interval,           "world.sense_requested"),
            (self.config.reality_check_interval,         "reality.check_requested"),
            (self.config.goal_generation_interval,       "goals.generation_requested"),
            (self.config.ego_maintenance_interval,       "ego.maintenance_requested"),
            (self.config.prediction_cycle_interval,      "prediction.cycle_requested"),
            (self.config.inner_monologue_interval,       "inner_monologue.requested"),
            (self.config.consolidation_interval,         "memory.consolidation_requested"),
            (self.config.decay_interval,                 "memory.decay_requested"),
            (self.config.dream_interval,                 "dream.requested"),
            (self.config.curiosity_interval,             "curiosity.scan_requested"),
            (self.config.concept_exploration_interval,   "concepts.exploration_requested"),
            (self.config.consciousness_metrics_interval, "consciousness.metrics_requested"),
            (self.config.temporal_check_interval,        "temporal.check_requested"),
            (self.config.prompt_evolution_interval,      "prompts.evolution_requested"),
        ]
        for interval, event_name in schedules:
            self._scheduler.add_job(
                self._emit_event, "interval", seconds=interval,
                args=[event_name, {}], id=f"emit_{event_name}", replace_existing=True,
            )
        self._scheduler.start()

    async def _fallback_scheduler(self) -> None:
        intervals = {
            "world.sense_requested":           self.config.world_sense_interval,
            "goals.generation_requested":      self.config.goal_generation_interval,
            "ego.maintenance_requested":       self.config.ego_maintenance_interval,
            "consciousness.metrics_requested": self.config.consciousness_metrics_interval,
            "temporal.check_requested":        self.config.temporal_check_interval,
            "memory.consolidation_requested":  self.config.consolidation_interval,
            "memory.decay_requested":          self.config.decay_interval,
        }
        last_fired = {k: 0.0 for k in intervals}
        while self._running:
            now = time.time()
            for event_name, interval in intervals.items():
                if now - last_fired[event_name] >= interval:
                    await self._emit_event(event_name, {})
                    last_fired[event_name] = now
            await asyncio.sleep(10)

    async def _emit_event(self, event_name: str, payload: Dict[str, Any]) -> None:
        loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
        if not loop:
            return
        event_task_map = {
            "world.sense_requested":           ("world_sense",          0.5),
            "reality.check_requested":         ("reality_check",        0.6),
            "goals.generation_requested":      ("goal_generation",      0.7),
            "ego.maintenance_requested":       ("ego_maintenance",      0.65),
            "prediction.cycle_requested":      ("prediction_cycle",     0.5),
            "inner_monologue.requested":       ("inner_monologue",      0.4),
            "memory.consolidation_requested":  ("consolidation",        0.5),
            "memory.decay_requested":          ("decay",                0.3),
            "dream.requested":                 ("dream",                0.3),
            "curiosity.scan_requested":        ("curiosity",            0.55),
            "concepts.exploration_requested":  ("concept_exploration",  0.45),
            "consciousness.metrics_requested": ("consciousness_metrics",0.4),
            "temporal.check_requested":        ("temporal_check",       0.5),
            "prompts.evolution_requested":     ("prompt_evolution",     0.35),
        }
        task_type, priority = event_task_map.get(event_name, ("unknown", 0.3))
        # Affect-bias priority
        try:
            state = self.emms.affect_state()
            if state.get("arousal", 0) > 0.5 and task_type in ("goal_generation", "reality_check", "world_sense"):
                priority = min(1.0, priority + 0.15)
            if state.get("valence", 0) < -0.3 and task_type in ("ego_maintenance", "consciousness_metrics"):
                priority = min(1.0, priority + 0.1)
        except Exception:
            pass
        loop.push_task(task_type=task_type, priority=priority, payload=payload)

    # ──────────────────────────────────────────────
    # Task Processors
    # ──────────────────────────────────────────────

    def _register_task_processors(self) -> None:
        loop = getattr(self.emms, "_get_cognitive_loop", lambda: None)()
        if not loop:
            logger.warning("No CognitiveLoop available — task processing disabled")
            return
        processors = {
            "world_sense":          self._process_world_sense,
            "reality_check":        self._process_reality_check,
            "goal_generation":      self._process_goal_generation,
            "ego_maintenance":      self._process_ego_maintenance,
            "prediction_cycle":     self._process_prediction_cycle,
            "inner_monologue":      self._process_inner_monologue,
            "consolidation":        self._process_consolidation,
            "decay":                self._process_decay,
            "dream":                self._process_dream,
            "curiosity":            self._process_curiosity,
            "concept_exploration":  self._process_concept_exploration,
            "consciousness_metrics":self._process_consciousness_metrics,
            "temporal_check":       self._process_temporal_check,
            "prompt_evolution":     self._process_prompt_evolution,
            "abductive_reasoning":  self._process_abductive_reasoning,
            "belief_revision":      self._process_belief_revision,
            "investigate_mismatch": self._process_investigate_mismatch,
            "replan_goal":          self._process_replan_goal,
            "emotional_regulation": self._process_emotional_regulation,
        }
        for task_type, processor in processors.items():
            if hasattr(loop, "register_processor"):
                loop.register_processor(task_type, processor)
            self._task_processors[task_type] = processor

    async def _process_world_sense(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 5: Sense the environment."""
        try:
            readings = self.emms.world_scan()
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "readings": len(readings)}
        except Exception:
            return {"status": "skipped"}

    async def _process_reality_check(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 5: Cross-reference beliefs against reality."""
        try:
            beliefs = self.emms.live_beliefs()
            results = self.emms.reality_check_batch([
                {"text": str(b), "domain": "general", "confidence": 0.5}
                for b in beliefs[:5]
            ])
            mismatches = [r for r in results if r.get("status") == "contradicted"]
            for m in mismatches:
                await self._emit_event("reality.mismatch", m)
            self._stats["tasks_completed"] += 1
            self._stats["reality_checks"] += len(results)
            return {"status": "complete", "checks": len(results), "mismatches": len(mismatches)}
        except Exception:
            return {"status": "skipped"}

    async def _process_goal_generation(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 4: Generate autonomous goals from 5 sources."""
        try:
            goals = self.emms.generate_autonomous_goals()
            self._stats["goals_generated"] += len(goals)
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "goals": len(goals)}
        except Exception:
            return {"status": "skipped"}

    async def _process_ego_maintenance(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 6: Update self-model."""
        try:
            summary = self.emms.live_self_model_summary()
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "summary_len": len(summary)}
        except Exception:
            return {"status": "skipped"}

    async def _process_prediction_cycle(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            pending = self.emms.pending_predictions() if hasattr(self.emms, "pending_predictions") else []
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "pending": len(pending) if isinstance(pending, list) else 0}
        except Exception:
            return {"status": "skipped"}

    async def _process_inner_monologue(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 1: Internal reflection."""
        try:
            state = self.emms.affect_state()
            self.emms.cognitive_loop_push(
                task_type="consolidate",
                description=f"Inner monologue: v={state.get('valence', 0):.2f} a={state.get('arousal', 0):.2f}",
                domain="ego",
            )
            self._stats["tasks_completed"] += 1
            return {"status": "complete"}
        except Exception:
            return {"status": "skipped"}

    async def _process_consolidation(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            mem = self.emms.memory
            dedup = mem.deduplicate() if hasattr(mem, "deduplicate") else 0
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "deduped": dedup}
        except Exception:
            return {"status": "skipped"}

    async def _process_decay(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            mem = self.emms.memory
            decayed = mem.apply_decay() if hasattr(mem, "apply_decay") else 0
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "decayed": decayed}
        except Exception:
            return {"status": "skipped"}

    async def _process_dream(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            self.emms.dream() if hasattr(self.emms, "dream") else None
            self._stats["tasks_completed"] += 1
            return {"status": "complete"}
        except Exception:
            return {"status": "skipped"}

    async def _process_curiosity(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            report = self.emms.curiosity_report() if hasattr(self.emms, "curiosity_report") else {}
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "gaps": len(report.get("goals", [])) if isinstance(report, dict) else 0}
        except Exception:
            return {"status": "skipped"}

    async def _process_concept_exploration(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 7: Explore conceptual space."""
        try:
            result = self.emms.explore_concepts()
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "holes": result.get("total_found", 0) if isinstance(result, dict) else 0}
        except Exception:
            return {"status": "skipped"}

    async def _process_consciousness_metrics(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            metrics = self.emms.get_consciousness_state() if hasattr(self.emms, "get_consciousness_state") else {}
            self._stats["tasks_completed"] += 1
            return {"status": "complete", **(metrics if isinstance(metrics, dict) else {})}
        except Exception:
            return {"status": "skipped"}

    async def _process_temporal_check(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 5: Process temporal anchors."""
        try:
            fired = self.emms.temporal_tick()
            for anchor in (fired if isinstance(fired, list) else []):
                if isinstance(anchor, dict) and anchor.get("type") == "deadline":
                    await self._emit_event("goal.stalling", anchor)
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "fired": len(fired) if isinstance(fired, list) else 0}
        except Exception:
            return {"status": "skipped"}

    async def _process_prompt_evolution(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 2: Evolve prompt strategies."""
        try:
            report = self.emms.evolve_prompt_strategies()
            self._stats["tasks_completed"] += 1
            return {"status": "complete", **(report if isinstance(report, dict) else {})}
        except Exception:
            return {"status": "skipped"}

    async def _process_abductive_reasoning(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 7: Generate hypotheses for surprising observations."""
        observation = payload.get("observation", "")
        if not observation:
            return {"status": "skipped"}
        try:
            hyps = self.emms.generate_hypotheses(observation=observation, domain=payload.get("domain", "general"))
            self._stats["hypotheses_created"] += len(hyps) if isinstance(hyps, list) else 0
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "hypotheses": len(hyps) if isinstance(hyps, list) else 0}
        except Exception:
            return {"status": "skipped"}

    async def _process_belief_revision(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            if hasattr(self.emms, "revise_beliefs"):
                self.emms.revise_beliefs()
            self._stats["tasks_completed"] += 1
            return {"status": "complete"}
        except Exception:
            return {"status": "skipped"}

    async def _process_investigate_mismatch(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Investigate a reality mismatch."""
        try:
            hyps = self.emms.generate_hypotheses(
                observation=payload.get("belief", "unknown mismatch"),
                domain=payload.get("domain", "general"),
            )
            if hyps:
                self.emms.verify_reasoning(
                    steps=[h.get("explanation", str(h)) for h in (hyps if isinstance(hyps, list) else [])],
                )
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "hypotheses": len(hyps) if isinstance(hyps, list) else 0}
        except Exception:
            return {"status": "skipped"}

    async def _process_replan_goal(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        try:
            plan = self.emms.plan_goal(
                goal_description=payload.get("description", "unknown goal"),
                domain=payload.get("domain", "general"),
            )
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "plan_id": plan.get("plan_id") if isinstance(plan, dict) else None}
        except Exception:
            return {"status": "skipped"}

    async def _process_emotional_regulation(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Gap 3: Regulate negative emotional state."""
        try:
            state = self.emms.affect_state()
            if state.get("valence", 0) < -0.3:
                self.emms.affect_update(
                    valence=state["valence"] * 0.7,
                    arousal=state.get("arousal", 0.3) * 0.8,
                )
            self._stats["tasks_completed"] += 1
            return {"status": "complete", "new_valence": self.emms.affect_state().get("valence", 0)}
        except Exception:
            return {"status": "skipped"}

    # ──────────────────────────────────────────────
    # Stats & REST API
    # ──────────────────────────────────────────────

    def stats(self) -> Dict[str, Any]:
        uptime = time.time() - self._stats["started_at"] if self._stats["started_at"] else 0
        return {
            **self._stats,
            "uptime_seconds": uptime,
            "uptime_human": f"{uptime / 3600:.1f}h",
            "task_processor_count": len(self._task_processors),
            "event_handler_count": len(self._event_handlers),
        }

    def register_routes(self, app: Any) -> None:
        """Register v2 REST endpoints with Flask app."""
        from flask import jsonify

        @app.route("/v2/stats")
        def v2_stats():
            return jsonify(self.stats())

        @app.route("/v2/autonomous_goals")
        def v2_autonomous_goals():
            try:
                return jsonify({"goals": self.emms.generate_autonomous_goals()})
            except Exception as e:
                return jsonify({"error": str(e)}), 503

        @app.route("/v2/pending_approvals")
        def v2_pending_approvals():
            return jsonify({"pending": self.emms.pending_approvals()})

        @app.route("/v2/approve/<int:index>", methods=["POST"])
        def v2_approve(index: int):
            return jsonify(self.emms.approve_action(index))

        @app.route("/v2/world")
        def v2_world():
            return jsonify({"readings": self.emms.world_scan()})

        @app.route("/v2/temporal")
        def v2_temporal():
            return jsonify({"summary": self.emms.temporal_summary(), "deadlines": self.emms.temporal_deadlines()})

        @app.route("/v2/hypotheses")
        def v2_hypotheses():
            return jsonify({"hypotheses": self.emms.active_hypotheses()})

        @app.route("/v2/affect")
        def v2_affect():
            return jsonify(self.emms.affect_state())

        @app.route("/v2/cognitive_loop")
        def v2_cognitive_loop():
            return jsonify(self.emms.cognitive_loop_metrics())


# ---------------------------------------------------------------------------
# Entry point (called by run_daemon.py --v2)
# ---------------------------------------------------------------------------

def main() -> None:
    """Self-contained entry point for ConsciousnessDaemonV2."""
    import asyncio
    import signal
    import json
    from pathlib import Path

    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
    logger = logging.getLogger("emms.daemon_v2")

    state_path = Path.home() / ".emms" / "emms_state.json"
    status_path = Path.home() / ".emms" / "daemon_status.json"

    # Load EMMS — reuse v1's load helpers
    try:
        from emms import EMMS
        emms = EMMS()
        if state_path.exists():
            emms.load(str(state_path))
            logger.info("Loaded EMMS state from %s", state_path)
        else:
            logger.warning("No state file at %s — starting fresh", state_path)
    except Exception as exc:
        logger.error("Failed to load EMMS: %s", exc, exc_info=True)
        return

    config = DaemonConfig()
    daemon = ConsciousnessDaemonV2(emms, config)

    def _write_status(phase: str) -> None:
        try:
            status_path.parent.mkdir(parents=True, exist_ok=True)
            status_path.write_text(json.dumps({"phase": phase, "version": "v2"}, indent=2))
        except Exception:
            pass

    async def _run() -> None:
        await daemon.start()
        _write_status("running")
        logger.info("ConsciousnessDaemonV2 running (event-driven mode)")
        try:
            while daemon._running:
                await asyncio.sleep(5)
        finally:
            await daemon.stop()
            _write_status("stopped")
            try:
                state_path.parent.mkdir(parents=True, exist_ok=True)
                emms.save(str(state_path))
                logger.info("EMMS state saved to %s", state_path)
            except Exception as exc:
                logger.error("Failed to save EMMS state: %s", exc)

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    def _shutdown(sig, frame):
        logger.info("Shutdown signal received (%s)", sig)
        daemon._running = False

    signal.signal(signal.SIGTERM, _shutdown)
    signal.signal(signal.SIGINT, _shutdown)

    try:
        loop.run_until_complete(_run())
    finally:
        loop.close()
